# DSpace Handle Server Docker image build for hub.docker.com
name: Docker images

# Run this Build for all pushes to 'master' or tagged releases.
# Also run for PRs to ensure PR doesn't break Docker build process
# NOTE: uses "reusable-docker-build.yml" to actually build each of the Docker images.
on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  ###################################################################
  # Build/Push the 'kstatelibraries/krex-dspace-handleserver' image.
  ###################################################################
  dspace-handle-server:
    # Ensure this job never runs on forked repos. It's only executed for 'kstatelibraries/docker-dspace-handle'
    if: github.repository == 'kstatelibraries/docker-dspace-handle'
    uses: kstatelibraries/kstatelibraries/.github/workflows/reusable-docker-build.yml@main
    with:
      build_id: dspace-handle-server
      image_name: kstatelibraries/krex-dspace-handleserver:test
      dockerfile_path: ./Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
